# -*- coding: utf-8 -*-
"""Lista2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jPdoi6GQggzkNX9gz8CLHLrtJgZdEpwv

ATIVIDADE 1
"""

num1 = int(input("Digite o primeiro número: "))
num2 = int(input("Digite o segundo número: "))
if num1 > num2:
    print(f"O primeiro número ({num1}) é maior que o segundo número ({num2}).")
elif num2 > num1:
    print(f"O segundo número ({num2}) é maior que o primeiro número ({num1}).")

"""ATIVIDADE 2

"""

pessoa1 = (input("Digite o nome da primeira pessoa: "))
altura1 =float(input("Digite a altura da primeira pessoa: "))
pessoa2 = (input("Digite o nome da segunda pessoa: "))
altura2 =float(input("Digite a altura da segunda pessoa: "))
if altura1 > altura2:
    print(f"A primeira pessoa ({pessoa1}) é maior que a segunda pessoa ({pessoa2}).")
elif altura2 > altura1:
    print(f"A segunda pessoa ({pessoa2}) é maior que a primeira pessoa ({pessoa1}).")

"""ATIVIDADE 3

"""

valor = float(input("Digite o valor do produto: R$"))
if valor >= 100:
    desconto = (valor * 10.0)/100
    valor = valor - desconto
    print ("O valor final é: R$", valor)
else:
  print ("O valor final é: R$", valor)

"""ATIVIDADE 4"""

pessoa1 = (input("Digite o nome da primeira pessoa: "))
ano1 = int(input("Digite o ano em que "+ pessoa1 +" nasceu: "))
pessoa2 = (input("Digite o nome da segunda pessoa: "))
ano2 =int(input("Digite o ano em que "+ pessoa2 +" nasceu: "))

idade1 = 2026 - ano1
idade2 = 2026 - ano2

if idade1 > idade2:
    print(f"{pessoa1} tem {idade1} e é mais velho que {pessoa2}, que tem {idade2}.")

else:
    print(f"{pessoa2} tem {idade2} e é mais velho que {pessoa1}, que tem {idade1}.")

"""ATIVIDADE 5"""

num = int(input("Digite o número: "))
if num % 2 == 0:
  print("O número é par.")
else:
  print("O número é ímpar.")

"""ATIVIDADE 6"""

meta = float(input("Qual o valor da meta a ser alcançada: R$"))
vendas = float(input("Qual o valor das vendas: R$"))
if vendas >= meta:
  print("Parabéns! Você atingiu a meta e ganhou o prêmio!")
else:
  print("Infelizmente você não ganhou o prêmio.")

"""ATIVIDADE 7"""

login = input("Digite o nome do usuário: ")
senha = input("Digite a senha: ")
if len(senha) < 8 or len(senha) > 12:
  print("ERRO: A senha deve conter entre 8 e 12 caracteres.")
else:
  print(f"Usuário {login} criado com sucesso.")

"""ATIVIDADE 8"""

nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
nota3 = float(input("Digite a terceira nota: "))
nota4 = float(input("Digite a quarta nota: "))
media = (nota1 + nota2 + nota3 + nota4)/4

faltas = int(input("Digite o número de faltas: "))

if faltas >= 10:
  print("Reprovado por faltas")
elif media >= 7:
  print("Aprovado")
elif media >= 5 and media < 7:
  print("Recuperação")
else:
  print("Reprovado")

"""ATIVIDADE 9"""

num1 = int(input("Digite o primeiro número: "))
num2 = int(input("Digite o segundo número: "))
if num1 == num2:
    print("Os números são iguais")
else:
    print("Os números são diferentes")