# -*- coding: utf-8 -*-
"""lista1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_d8wxvikDvqIv8z1unK7vJYtG6OscEqf

Atividade 1
"""

nome = input('Digite o seu nome: ')
sobrenome = input('Digite o seu sobrenome: ')
nome_completo = nome + ' ' + sobrenome
print ('Seu nome completo é ', nome_completo )

"""Atividade 2

"""

numero1 = float (input ('Digite um número: '))
numero2 = float (input ('Digite outro número:'))
diferenca = numero1 - numero2

print ('A diferença é ', diferenca)

"""Atividade 3

"""

numA = int(input('Digite um número: '))
numB = int(input('Digite outro número: '))
print (numB)
print (numA)

"""Atividade 4

"""

prova1 = float(input('Nota da 1° prova: ') )
prova1 = prova1 * 2.0

prova2 = float(input('Nota da 2° prova: '))
prova2 = prova2 * 3.0

prova3 = float(input('Nota da 3° prova: '))
prova3 = prova3 * 5.0

media = (prova1 + prova2 + prova3)/10.0

print ('A média é ', media)

"""Atividade 5

"""

altura = input("Digite a altura da caixa: ")
largura = input("Digite a largura da caixa: ")
profundidade = input("Digite a profundidade da caixa: ")

volume = float(altura) * float(largura) * float(profundidad

"""Atividade 6

"""

base = input("Digite a base do triângulo: ")
altura = input("Digite a altura do triângulo: ")

area = (int(base) * int(altura)) / 2

print("A área do triângulo é: " + str(area))